version: '3.5'

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './:/var/www'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/logs:/var/log/nginx/'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - backend

  php-8.0:
    build:
      context: docker/php/8.0
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '8.0'
    working_dir: /var/www
    container_name: php-8.0
    volumes:
      - './:/var/www'
      - './docker/php/8.0/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - "9000:9000"
    networks:
      - backend
